### ISSUE TITLE
Mask Script

### ISSUE THREAD

**Issue by julbrandt** [NSLS-II-CHX/CHX_BugReport#10]
I'm having issues with the mask script. I am using the Mask_Pipeline_June.ipnb and when I get to the create manual mask step, the entire image is blank. I noticed that the step that shows the md['pixel_mask'] looks backwards, in other words the area we don't want to mask are zeros. Below is a screen shot:

![chx_mask_issue](https://cloud.githubusercontent.com/assets/20361953/18556998/30218d3c-7b3b-11e6-86ba-7022af00a019.png)

Did the pixel_mask change or did I mess up the script somehow?

**Comment by yugangzhang** [comment]
julbrandt, you are right. The pixel_mask changed. Recently, the data analysis package is corrupt. We update the code and the mask function was updated with an old code. 

Please use the following code to make the pixel_maks inverse (make 0 to 1 and 1 to 0)

 md['pixel_mask'] =  1- np.int_( np.array( md['pixel_mask'], dtype= bool)  )

**Comment by julbrandt** [comment]
Thank you, it works now.

Jeff

**Comment by yugangzhang** [comment]
Jeff, can you give a notebook pipeline you are working on? We recently developed a fast algorithm to do time correlation. I can use the uid/data in your provided pipeline to create an example notebook for you, and then you can play with it.

**Comment by julbrandt** [comment]
Yugang, here is a link to a pipeline:

https://notebook-backup.nsls2.bnl.gov/user/julbrand/notebooks/analysis/julbrand/XPCS_GiSAXS_2016_June_Si_sam1_early_time_35e040.ipynb

**Comment by yugangzhang** [comment]
Great, Thanks!

**Comment by yugangzhang** [comment]
An announcement from NSLS-II data acquisition group:

```
https://notebook.nsls2.bnl.gov has been fixed. The reliability problems were due to a hardware failure, as it turns out. Please go back to using notebook..., not notebook-backup or a locally-run server. Please report any problems you have. If there are other issues, identifying them and fixing them is a high priority. We want to achieve high reliability on this system.

```

**Comment by julbrandt** [comment]
Hi Yugang, I ran into another issue with the mask pipeline. On the manual mask step we are supposed to press 'i' and then draw a mask. When I press 'i' I do not get the "lasso" on the bottom right, nor can I draw a mask. Also, I am unable to move on to the rectangle mask step because m.mask is all false.
Thanks, Jeff

**Comment by yugangzhang** [comment]
@julbrandt I got the same problem. It seems like the ManualMask package does not work. We have to take a deep look at it. But, usually, we use a code to generate a mask rather than manually making. I put an example pipeline in 
https://github.com/NSLS-II-CHX/CHX_Pipelines/blob/master/Mask_pipeline_Aug_template.ipynb

Please take a look at "Create a polygon mask" part. It allows you easily to make any shaped mask by giving the vertices coordinates.
