### ISSUE TITLE
fit_gisaxs_g2 error

### ISSUE THREAD

**Issue by julbrandt** [NSLS-II-CHX/CHX_BugReport#12]
There seems to be a bug in the fit_gisaxs_g2 function when choosing "simple":

![fit_error](https://cloud.githubusercontent.com/assets/20361953/18639027/52f512fc-7e60-11e6-9b76-83d677a43f64.png)

**Comment by yugangzhang** [comment]
Please take a look at our latest pipelines at 
https://github.com/NSLS-II-CHX/CHX_Pipelines
I also created a gisaxs for @julbrandt as XPCS_GiSAXS_Example_35e040.ipynb.

@julbrandt can use the fitting setup in the example pipeline for your analysis.
