### ISSUE TITLE
Can't load data error

### ISSUE THREAD

**Issue by rheadric** [NSLS-II-CHX/CHX_BugReport#13]
There may be some problem with the server.  In my workbook Open_Image_by_Knowing_UID_V2, I get:

detector = get_detector( db[uid ] )

print ('Detector is:  %s'%detector  )

sud = get_sid_filenames(db[uid])

print ('scan_id, full-uid, data path are:  %s--%s--%s'%(sud[0], sud[1], sud[2][0] ))

imgs = load_data( uid, detector  )

md = imgs.md

Detector is:  eiger4m_single_image
scan_id, full-uid, data path are:  2870--160c816a-8ba8-45cd-a708-a973bdd61379--/XF11ID/data/2016/10/14/d5164601-ffd0-4303-a661_2390
Trying again ...!
Can't Load Data!

---

AttributeError                            Traceback (most recent call last)
<ipython-input-4-7aef06a6ffa2> in <module>()
      4 print ('scan_id, full-uid, data path are:  %s--%s--%s'%(sud[0], sud[1], sud[2][0] ))
      5 imgs = load_data( uid, detector  )
----> 6 md = imgs.md

AttributeError: 'int' object has no attribute 'md'

**Comment by rheadric** [comment]
Update:  I noticed the comment on #9 about the old server  https://notebook-backup.nsls2.bnl.gov
I can load data with the old server, but still get the same error with https://notebook.nsls2.bnl.gov

**Comment by yugangzhang** [comment]
On the new sever:  https://notebook.nsls2.bnl.gov

please add 
```
from chxtools.handlers import LazyEigerHandler
db.fs.register_handler('AD_EIGER', LazyEigerHandler)
```
after the import package cell.

The new sever is not stable, please use the old sever and we will let you know when the new sever is ready to use.

**Comment by yugangzhang** [comment]
can we close it?
