### ISSUE TITLE
plot_g2_general labels the plots incorrectly

### ISSUE THREAD

**Issue by rheadric** [NSLS-II-CHX/CHX_BugReport#18]
I am working with Jupyter notebooks in the 2017_3 directory:

XPCS_Single_2017_V8_with_Monitor_Beam_d0f799_V2
XPCS_Setup_2017_V7_with_ReflMonitor_d0f799_Detector_Shift_V2

`plot_g2_general` labels the plots with incorrect Qr values. The `qval_dict` listed below appears to be correct:

`{0: array([ 0.00365,  0.0455 ]),
 1: array([ 0.00895,  0.0455 ]),
 2: array([ 0.01425,  0.0455 ]),
 3: array([ 0.01955,  0.0455 ]),
 4: array([ 0.02485,  0.0455 ]),
 5: array([ 0.03015,  0.0455 ]),
 6: array([ 0.03545,  0.0455 ]),
 7: array([ 0.04075,  0.0455 ]),
 8: array([ 0.04605,  0.0455 ]),
 9: array([ 0.05135,  0.0455 ]),
 10: array([ 0.05665,  0.0455 ]),
 11: array([ 0.06195,  0.0455 ]),
 12: array([ 0.00365,  0.0545 ]),
 13: array([ 0.00895,  0.0545 ]),
 14: array([ 0.01425,  0.0545 ]),
 15: array([ 0.01955,  0.0545 ]),
 16: array([ 0.02485,  0.0545 ]),
 17: array([ 0.03015,  0.0545 ]),
 18: array([ 0.03545,  0.0545 ]),
 19: array([ 0.04075,  0.0545 ]),
 20: array([ 0.04605,  0.0545 ]),
 21: array([ 0.05135,  0.0545 ]),
 22: array([ 0.05665,  0.0545 ]),
 23: array([ 0.06195,  0.0545 ]),
 24: array([ 0.0006,  0.068 ])}`

For example, plot (1) is labelled as 0.0006, while it should be 0.00365.  And plots (2) and (3) are labelled 0.00365 when they should be 0.00895 and 0.01425 respexctively.

**Comment by yugangzhang** [comment]
@rheadric  It is really a bug. I corrected the source code and it will work after you restart the kernel. 
I also put the pipeline with corrected plot in 
https://github.com/NSLS-II-CHX/CHX_BugReport/tree/master/Bug_Cor_Pipelines
