### ISSUE TITLE
A test example

### ISSUE THREAD

**Issue by yugangzhang** [NSLS-II-CHX/CHX_BugReport#2]
```
This is a bug report test!

```

**Comment by yugangzhang** [comment]
Problem solved!

**Comment by ericdill** [comment]
What is the advantage of using this repo over the one that we have been using for these problems at https://github.com/nsls-ii/Bug-Reports?

**Comment by yugangzhang** [comment]
The purpose of the chx bug report is only for chx (user) data analysis. Previously, the only way for chx users to report problem is to send me emails. They also have to cc to others. The chx bug report should provide a better platform to support users.

Does this make sense to you?



Sent from my iPhone

On Jun 30, 2016, at 6:09 PM, Eric Dill <notifications@github.com<mailto:notifications@github.com>> wrote:


What is the advantage of using this repo over the one that we have been using for these problems at https://github.com/nsls-ii/Bug-Reports?

**Comment by danielballan** [comment]
That seems reasonable to me. There was also talk of setting up a chatroom (using a technology like Slack or gitter) which could be watched by group members, DAMA members, members of Petkus's group, etc.
