### ISSUE TITLE
g2 plots missing axes when only 1 qr region is used

### ISSUE THREAD

**Issue by julbrandt** [NSLS-II-CHX/CHX_BugReport#5]
When plotting the g2 functions and only defining 1 qr region, the resulting plots do not have any axes. The axes show up when two or more qr regions are defined. The function which calls the plots is: plot_gisaxs_g2.

Jeff

**Comment by yugangzhang** [comment]
I updated the code ```plot_gisaxs_g2```. Please restart your kernel and try.

**Comment by julbrandt** [comment]
Sorry, forgot to close this. This issues is resolved. Thanks.
