### ISSUE TITLE
get_each_frame_intensity error

### ISSUE THREAD

**Issue by rheadric** [NSLS-II-CHX/CHX_BugReport#7]
imgsum, bad_frame_list = get_each_frame_intensity(good_series ,sampling = 1, 
                                bad_pixel_threshold=4e9,  plot_ = True, uid=uid)

produces:
.
.
.
--> 399         if save:
    400             #dt =datetime.now()
    401             #CurTime = '%s%02d%02d-%02d%02d-' % (dt.year, dt.month, dt.day,dt.hour,dt.minute)

NameError: name 'save' is not defined

However, the function works fine with plot_=False.

**Comment by yugangzhang** [comment]
I updated the code and put "save" option in the function. It should work now.
